Repository evannetwork/vade-sidetree, pull requests merged in 2023-02, with the labels that each got.

#8 Adjust sidetree api to allow nonces and refactor input params
  .github/test.yml
  src/datatypes.rs
  src/lib.rs
  src/vade_sidetree.rs
  vade-sidetree-client/src/did.rs
  vade-sidetree-client/src/lib.rs
  vade-sidetree-client/src/operations.rs
  vade-sidetree-client/src/secp256k1.rs
Labels: enhancement

#9 Fix in3 request list fallback payload
  VERSIONS.md
  src/in3_request_list.rs
Labels: bug

#10 Fix in3 request list fallback payload
  src/in3_request_list.rs
  src/vade_sidetree.rs
Labels: bug

#12 Merge changes from sdk branch
  Cargo.lock
  Cargo.toml
  VERSIONS.md
  src/datatypes.rs
  src/in3_request_list.rs
  src/lib.rs
  src/vade_sidetree.rs
Labels: enhancement

#11 Fix update with nonce
  .github/workflows/test.yml
  Cargo.lock
  src/vade_sidetree.rs
  vade-sidetree-client/Cargo.toml
  vade-sidetree-client/src/operations.rs
  vade-sidetree-client/src/secp256k1.rs
Labels: bug, enhancement
